# frozen_string_literal: true

module RailsOpenapiGen
  class Configuration
    attr_accessor :openapi_version, :info, :servers, :route_patterns, :output

    def initialize
      @openapi_version = "3.0.0"
      @info = {
        title: default_app_name,
        version: "1.0.0",
        description: "API documentation generated by rails-openapi-gen"
      }
      @servers = [
        {
          url: "http://localhost:3000",
          description: "Development server"
        }
      ]
      @route_patterns = {
        include: [/.*/], # Include all routes by default
        exclude: []      # Exclude nothing by default
      }
      @output = {
        directory: "openapi",
        filename: "openapi.yaml",
        split_files: true
      }
    end

    def load_from_file(file_path = nil)
      if file_path
        return unless File.exist?(file_path)
      else
        # Try different config file paths in order of preference
        config_paths = [
          Rails.root.join("config", "openapi.rb"),
          Rails.root.join("config", "initializers", "openapi.rb")
        ]
        
        file_path = config_paths.find { |path| File.exist?(path) }
        return unless file_path
      end

      load_ruby_config(file_path)
    end

    def output_directory
      if @output[:directory].start_with?('/')
        @output[:directory]
      else
        File.join(Rails.root.to_s, @output[:directory])
      end
    end

    def output_filename
      @output[:filename]
    end

    def split_files?
      @output[:split_files]
    end

    def update_output_config(output_config)
      load_output_config(output_config)
    end

    def route_included?(path)
      # Check if path matches any include pattern
      included = @route_patterns[:include].any? { |pattern| path.match?(pattern) }
      return false unless included

      # Check if path matches any exclude pattern
      excluded = @route_patterns[:exclude].any? { |pattern| path.match?(pattern) }
      !excluded
    end

    private

    def load_ruby_config(file_path)
      # Load Ruby configuration file
      # The file should call RailsOpenapiGen.configure block
      load file_path
    end

    def default_app_name
      if defined?(Rails) && Rails.application
        Rails.application.class.respond_to?(:module_parent_name) ? 
          Rails.application.class.module_parent_name : 
          "RailsApp"
      else
        "API"
      end
    end

    def symbolize_keys(hash)
      return hash unless hash.is_a?(Hash)
      hash.transform_keys(&:to_sym)
    end


    def load_output_config(output_config)
      output_settings = symbolize_keys(output_config)
      
      @output[:directory] = output_settings[:directory] if output_settings[:directory]
      @output[:filename] = output_settings[:filename] if output_settings[:filename]
      @output[:split_files] = output_settings[:split_files] if output_settings.key?(:split_files)
    end
  end

  class << self
    attr_writer :configuration

    def configuration
      @configuration ||= Configuration.new
    end

    def configure
      yield(configuration)
    end

    def reset_configuration!
      @configuration = Configuration.new
    end
  end
end