---
openapi: 3.0.0
info:
  title: User Management API
  version: 1.2.0
  description: REST API for managing users and their profiles
  contact:
    name: API Support Team
    email: api-support@myapp.com
    url: https://myapp.com/support
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
- url: https://api.myapp.com
  description: Production server
- url: https://staging-api.myapp.com
  description: Staging server
- url: http://localhost:3000
  description: Development server
paths:
  "/posts/{post_id}/comments":
    get:
      summary: Index Comment
      operationId: comments_index
      tags:
      - Comments
      parameters:
      - name: post_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: Unique comment identifier
                    content:
                      type: string
                      description: Comment content
                    author:
                      type: string
                      description: Comment author name
                    created_at:
                      type: string
                      description: Comment creation timestamp
                    likes:
                      type: integer
                      description: Number of likes on this comment
                  required:
                  - id
                  - content
                  - author
                  - created_at
                  - likes
  "/posts":
    get:
      summary: Index Post
      operationId: posts_index
      tags:
      - Posts
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: Unique post identifier
                    title:
                      type: string
                      description: Post title
                    content:
                      type: string
                      description: Post content/body
                    published:
                      type: boolean
                      description: Whether the post is published
                    created_at:
                      type: string
                      description: Post creation timestamp in ISO 8601 format
                    tags:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: integer
                            description: Tag unique identifier
                          color:
                            type: string
                            description: Tag color in hex format
                        required:
                        - name
                        - color
                  required:
                  - id
                  - title
                  - content
                  - published
                  - created_at
                  - tags
  "/posts/{id}":
    get:
      summary: Show Post
      operationId: posts_show
      tags:
      - Posts
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  author:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: User unique identifier
                      name:
                        type: string
                        description: User full name
                      email:
                        type: string
                        description: User email address
                      status:
                        type: string
                        description: Current user status
                        enum:
                        - active
                        - inactive
                        - suspended
                      created_at:
                        type: string
                        description: Account creation timestamp
                    required:
                    - id
                    - name
                    - email
                    - status
                    - created_at
                  tags:
                    type: array
                    items:
                      type: string
                    description: Post tags for categorization
                  comments_count:
                    type: integer
                    description: Total number of comments
                  likes_count:
                    type: integer
                    description: Total number of likes
                  published_at:
                    type: string
                    description: Publication timestamp
                  id:
                    type: integer
                    description: Post unique identifier
                  title:
                    type: string
                    description: Post title
                  content:
                    type: string
                    description: Post content body
                  published:
                    type: boolean
                    description: Whether the post is published
                  created_at:
                    type: string
                    description: Post creation timestamp
                  updated_at:
                    type: string
                    description: Last update timestamp
                required:
                - author
                - tags
                - comments_count
                - likes_count
                - published_at
                - id
                - title
                - content
                - published
                - created_at
                - updated_at
  "/users/{user_id}/posts":
    get:
      summary: Index Post
      operationId: posts_index
      tags:
      - Posts
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: Unique post identifier
                    title:
                      type: string
                      description: Post title
                    content:
                      type: string
                      description: Post content/body
                    published:
                      type: boolean
                      description: Whether the post is published
                    created_at:
                      type: string
                      description: Post creation timestamp in ISO 8601 format
                    tags:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: integer
                            description: Tag unique identifier
                          color:
                            type: string
                            description: Tag color in hex format
                        required:
                        - name
                        - color
                  required:
                  - id
                  - title
                  - content
                  - published
                  - created_at
                  - tags
    post:
      summary: Create Post
      operationId: posts_create
      tags:
      - Posts
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  post_id:
                    type: integer
                  created_at:
                    type: string
                required:
                - success
                - message
                - post_id
                - created_at
  "/users/{user_id}/posts/{id}":
    get:
      summary: Show Post
      operationId: posts_show
      tags:
      - Posts
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  author:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: User unique identifier
                      name:
                        type: string
                        description: User full name
                      email:
                        type: string
                        description: User email address
                      status:
                        type: string
                        description: Current user status
                        enum:
                        - active
                        - inactive
                        - suspended
                      created_at:
                        type: string
                        description: Account creation timestamp
                    required:
                    - id
                    - name
                    - email
                    - status
                    - created_at
                  tags:
                    type: array
                    items:
                      type: string
                    description: Post tags for categorization
                  comments_count:
                    type: integer
                    description: Total number of comments
                  likes_count:
                    type: integer
                    description: Total number of likes
                  published_at:
                    type: string
                    description: Publication timestamp
                  id:
                    type: integer
                    description: Post unique identifier
                  title:
                    type: string
                    description: Post title
                  content:
                    type: string
                    description: Post content body
                  published:
                    type: boolean
                    description: Whether the post is published
                  created_at:
                    type: string
                    description: Post creation timestamp
                  updated_at:
                    type: string
                    description: Last update timestamp
                required:
                - author
                - tags
                - comments_count
                - likes_count
                - published_at
                - id
                - title
                - content
                - published
                - created_at
                - updated_at
  "/users":
    get:
      summary: Index User
      operationId: users_index
      tags:
      - Users
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties: {}
                  required: []
  "/users/{id}":
    get:
      summary: Show User
      operationId: users_show
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  role:
                    type: string
                    description: User role in the system
                    enum:
                    - admin
                    - moderator
                    - user
                  profile:
                    type: object
                    properties:
                      bio:
                        type: string
                        description: User biography
                      avatar_url:
                        type: string
                        description: URL to user's avatar image
                      verified:
                        type: boolean
                        description: Whether the user's email is verified
                    required:
                    - bio
                    - avatar_url
                    - verified
                  posts:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: Post ID
                        title:
                          type: string
                          description: Post title
                        published:
                          type: boolean
                          description: Publication status
                      required:
                      - id
                      - title
                      - published
                  metadata:
                    type: object
                    properties:
                      last_login:
                        type: string
                        description: Last login timestamp
                      login_count:
                        type: integer
                        description: Total login count
                      account_type:
                        type: string
                        description: Account tier
                        enum:
                        - free
                        - premium
                        - enterprise
                    required:
                    - last_login
                    - login_count
                    - account_type
                  id:
                    type: integer
                    description: User unique identifier
                  name:
                    type: string
                    description: User full name
                  email:
                    type: string
                    description: User email address
                  status:
                    type: string
                    description: Current user status
                    enum:
                    - active
                    - inactive
                    - suspended
                  created_at:
                    type: string
                    description: Account creation timestamp
                required:
                - role
                - profile
                - posts
                - metadata
                - id
                - name
                - email
                - status
                - created_at
