# frozen_string_literal: true

module RailsOpenapiGen
  class Configuration
    attr_accessor :openapi_version, :info, :servers, :route_patterns, :output

    # Initializes configuration with default values
    def initialize
      @openapi_version = "3.0.0"
      @info = {
        title: default_app_name,
        version: "1.0.0",
        description: "API documentation generated by rails-openapi-gen"
      }
      @servers = [
        {
          url: "http://localhost:3000",
          description: "Development server"
        }
      ]
      @route_patterns = {
        include: [/.*/], # Include all routes by default
        exclude: []      # Exclude nothing by default
      }
      @output = {
        directory: "openapi",
        filename: "openapi.yaml",
        split_files: true
      }
    end

    # TODO: Loads configuration from Ruby file
    # @param file_path [String, nil] Path to configuration file (defaults to config/openapi.rb or config/initializers/openapi.rb)
    # @return [void]
    def load_from_file(file_path = nil)
      # If no file path provided, try to find configuration file automatically
      if file_path.nil?
        file_path = find_config_file
        return unless file_path
      end

      # Check if file exists
      unless File.exist?(file_path)
        puts "⚠️  Configuration file not found: #{file_path}" if ENV['RAILS_OPENAPI_DEBUG']
        return
      end

      puts "📁 Loading configuration from: #{file_path}" if ENV['RAILS_OPENAPI_DEBUG']

      # Load the configuration file
      if file_path.end_with?('.rb')
        load_ruby_config(file_path)
      elsif file_path.end_with?('.yml', '.yaml')
        load_yaml_config(file_path)
      else
        puts "❌ Unsupported configuration file format: #{file_path}"
      end
    end


    # Returns the full path to the output directory
    # @return [String] Full output directory path
    def output_directory
      if @output[:directory].start_with?('/')
        @output[:directory]
      else
        File.join(Rails.root.to_s, @output[:directory])
      end
    end

    # Returns the output filename
    # @return [String] Output filename
    def output_filename
      @output[:filename]
    end

    # Checks if output should be split into multiple files
    # @return [Boolean] True if files should be split
    def split_files?
      @output[:split_files]
    end

    # Updates output configuration
    # @param output_config [Hash] Output configuration hash
    # @return [void]
    def update_output_config(output_config)
      load_output_config(output_config)
    end

    # Checks if a route path should be included in the OpenAPI spec
    # @param path [String] Route path to check
    # @return [Boolean] True if route should be included
    def route_included?(path)
      # Ensure @route_patterns is properly initialized
      @route_patterns ||= { include: [/.*/], exclude: [] }
      
      # Check if path matches any include pattern
      included = (@route_patterns[:include] || []).any? { |pattern| path.match?(pattern) }
      return false unless included

      # Check if path matches any exclude pattern
      excluded = (@route_patterns[:exclude] || []).any? { |pattern| path.match?(pattern) }
      !excluded
    end

    private

    # Find configuration file in Rails application
    # @return [String, nil] Path to configuration file or nil if not found
    def find_config_file
      # Priority order for configuration files
      candidates = [
        'config/openapi.rb',
        'config/initializers/openapi.rb',
        'config/openapi.yml',
        'config/openapi.yaml'
      ]

      if defined?(Rails) && Rails.root
        candidates.each do |candidate|
          full_path = File.join(Rails.root, candidate)
          return full_path if File.exist?(full_path)
        end
      end

      nil
    end

    # Loads Ruby configuration file
    # @param file_path [String] Path to configuration file
    # @return [void]
    def load_ruby_config(file_path)
      # Save current configuration as backup
      old_config = RailsOpenapiGen.instance_variable_get(:@configuration)
      
      # Temporarily set this instance as the global configuration
      # so that the configure block updates this instance
      RailsOpenapiGen.instance_variable_set(:@configuration, self)
      
      begin
        # Load Ruby configuration file
        # The file should call RailsOpenapiGen.configure block
        load file_path
        puts "✅ Configuration loaded successfully" if ENV['RAILS_OPENAPI_DEBUG']
      rescue => e
        puts "❌ Error loading configuration: #{e.message}" if ENV['RAILS_OPENAPI_DEBUG']
        raise e
      ensure
        # Restore original global configuration
        RailsOpenapiGen.instance_variable_set(:@configuration, old_config)
      end
    end

    # Loads YAML configuration file
    # @param file_path [String] Path to YAML configuration file
    # @return [void]
    def load_yaml_config(file_path)
      require 'yaml'
      config_hash = YAML.load_file(file_path)
      
      # Apply YAML configuration to this instance
      config_hash.each do |key, value|
        case key.to_s
        when 'openapi_version'
          @openapi_version = value
        when 'info'
          @info = symbolize_keys(value)
        when 'servers'
          @servers = value.is_a?(Array) ? value : [value]
        when 'route_patterns'
          patterns = symbolize_keys(value)
          @route_patterns[:include] = Array(patterns[:include]).map { |p| Regexp.new(p) }
          @route_patterns[:exclude] = Array(patterns[:exclude]).map { |p| Regexp.new(p) }
        when 'output'
          @output = symbolize_keys(value)
        end
      end
      
      puts "✅ YAML configuration loaded successfully" if ENV['RAILS_OPENAPI_DEBUG']
    end

    # Returns default application name
    # @return [String] Default app name
    def default_app_name
      if defined?(Rails) && Rails.application
        Rails.application.class.respond_to?(:module_parent_name) ? 
          Rails.application.class.module_parent_name : 
          "RailsApp"
      else
        "API"
      end
    end

    # Converts hash keys to symbols
    # @param hash [Hash] Hash to convert
    # @return [Hash] Hash with symbolized keys
    def symbolize_keys(hash)
      return hash unless hash.is_a?(Hash)
      hash.transform_keys(&:to_sym)
    end


    # Loads output configuration settings
    # @param output_config [Hash] Output configuration hash
    # @return [void]
    def load_output_config(output_config)
      output_settings = symbolize_keys(output_config)
      
      @output[:directory] = output_settings[:directory] if output_settings[:directory]
      @output[:filename] = output_settings[:filename] if output_settings[:filename]
      @output[:split_files] = output_settings[:split_files] if output_settings.key?(:split_files)
    end
  end

  class << self
    attr_writer :configuration

    # Returns the configuration instance
    # @return [Configuration] Configuration instance
    def configuration
      @configuration ||= Configuration.new
    end

    # Configures the gem via block
    # @yield [Configuration] Configuration instance
    # @return [void]
    def configure
      yield(configuration)
    end

    # Resets configuration to defaults
    # @return [void]
    def reset_configuration!
      @configuration = Configuration.new
    end
  end
end